name: new workflow

on: [push]

jobs:
  hello-nedap:
    runs-on: ubuntu-latest
    steps:
      - name: setup java
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '17'
        run: java -cp java Main

